version: '3.4'

name: match-management

networks:
  match-management:

services:

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database
    environment:
      SA_PASSWORD: "123456q!"
      ACCEPT_EULA: "Y"
    ports:
        - "1444:1433"
    networks:
       - match-management

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: MatchManagement
      DB_SA_PASSWORD: "123456q!"
    networks:
       - match-management